[package]
name = "minicc"
version = "0.1.0"
authors = ["Felix Zhou <felix.rn.zhou@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
